version: "3.8"

tasks:
  install:
    cmds:
      - python -m venv venv
      - ./venv/Scripts/activate
      - pip install -r requirements.txt

  proto:
    cmds:
      - python -m grpc_tools.protoc -I. --proto_path=. --python_out=. --grpc_python_out=. ./app/protos/*.proto

  dev:
    cmds:
      - python dev.py

  prod:
    cmds:
      - python -m app.main
  test:
    cmds:
      - pytest tests/ -v
