# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: app/protos/app.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14\x61pp/protos/app.proto\x12\x03\x61pp\"\x14\n\x12HealthCheckRequest\"&\n\x13HealthCheckResponse\x12\x0f\n\x07message\x18\x01 \x01(\t\"\'\n\x15\x44omainClassifyRequest\x12\x0e\n\x06\x64omain\x18\x01 \x01(\t\"\'\n\x16\x44omainClassifyResponse\x12\r\n\x05label\x18\x01 \x03(\t2\x99\x01\n\nAppService\x12@\n\x0bHealthCheck\x12\x17.app.HealthCheckRequest\x1a\x18.app.HealthCheckResponse\x12I\n\x0e\x44omainClassify\x12\x1a.app.DomainClassifyRequest\x1a\x1b.app.DomainClassifyResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'app.protos.app_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_HEALTHCHECKREQUEST']._serialized_start=29
  _globals['_HEALTHCHECKREQUEST']._serialized_end=49
  _globals['_HEALTHCHECKRESPONSE']._serialized_start=51
  _globals['_HEALTHCHECKRESPONSE']._serialized_end=89
  _globals['_DOMAINCLASSIFYREQUEST']._serialized_start=91
  _globals['_DOMAINCLASSIFYREQUEST']._serialized_end=130
  _globals['_DOMAINCLASSIFYRESPONSE']._serialized_start=132
  _globals['_DOMAINCLASSIFYRESPONSE']._serialized_end=171
  _globals['_APPSERVICE']._serialized_start=174
  _globals['_APPSERVICE']._serialized_end=327
# @@protoc_insertion_point(module_scope)
