# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from app.protos import assistant_pb2 as app_dot_protos_dot_assistant__pb2


class AppServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.HealthCheck = channel.unary_unary(
                '/app.AppService/HealthCheck',
                request_serializer=app_dot_protos_dot_assistant__pb2.HealthCheckRequest.SerializeToString,
                response_deserializer=app_dot_protos_dot_assistant__pb2.HealthCheckResponse.FromString,
                )
        self.DomainClassify = channel.unary_unary(
                '/app.AppService/DomainClassify',
                request_serializer=app_dot_protos_dot_assistant__pb2.DomainClassifyRequest.SerializeToString,
                response_deserializer=app_dot_protos_dot_assistant__pb2.DomainClassifyResponse.FromString,
                )


class AppServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def HealthCheck(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DomainClassify(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AppServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'HealthCheck': grpc.unary_unary_rpc_method_handler(
                    servicer.HealthCheck,
                    request_deserializer=app_dot_protos_dot_assistant__pb2.HealthCheckRequest.FromString,
                    response_serializer=app_dot_protos_dot_assistant__pb2.HealthCheckResponse.SerializeToString,
            ),
            'DomainClassify': grpc.unary_unary_rpc_method_handler(
                    servicer.DomainClassify,
                    request_deserializer=app_dot_protos_dot_assistant__pb2.DomainClassifyRequest.FromString,
                    response_serializer=app_dot_protos_dot_assistant__pb2.DomainClassifyResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'app.AppService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class AppService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def HealthCheck(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/app.AppService/HealthCheck',
            app_dot_protos_dot_assistant__pb2.HealthCheckRequest.SerializeToString,
            app_dot_protos_dot_assistant__pb2.HealthCheckResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def DomainClassify(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/app.AppService/DomainClassify',
            app_dot_protos_dot_assistant__pb2.DomainClassifyRequest.SerializeToString,
            app_dot_protos_dot_assistant__pb2.DomainClassifyResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
