# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from app.protos import assistant_pb2 as app_dot_protos_dot_assistant__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in app/protos/assistant_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class HealthCheckStub(object):
    """----------------
    Health Check
    ----------------
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.HealthCheck = channel.unary_unary(
                '/app.HealthCheck/HealthCheck',
                request_serializer=app_dot_protos_dot_assistant__pb2.HealthCheckRequest.SerializeToString,
                response_deserializer=app_dot_protos_dot_assistant__pb2.HealthCheckResponse.FromString,
                _registered_method=True)


class HealthCheckServicer(object):
    """----------------
    Health Check
    ----------------
    """

    def HealthCheck(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_HealthCheckServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'HealthCheck': grpc.unary_unary_rpc_method_handler(
                    servicer.HealthCheck,
                    request_deserializer=app_dot_protos_dot_assistant__pb2.HealthCheckRequest.FromString,
                    response_serializer=app_dot_protos_dot_assistant__pb2.HealthCheckResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'app.HealthCheck', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('app.HealthCheck', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class HealthCheck(object):
    """----------------
    Health Check
    ----------------
    """

    @staticmethod
    def HealthCheck(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/app.HealthCheck/HealthCheck',
            app_dot_protos_dot_assistant__pb2.HealthCheckRequest.SerializeToString,
            app_dot_protos_dot_assistant__pb2.HealthCheckResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class DomainClassifyStub(object):
    """----------------
    Domain Classify
    ----------------
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.DomainClassify = channel.unary_unary(
                '/app.DomainClassify/DomainClassify',
                request_serializer=app_dot_protos_dot_assistant__pb2.DomainClassifyRequest.SerializeToString,
                response_deserializer=app_dot_protos_dot_assistant__pb2.DomainClassifyResponse.FromString,
                _registered_method=True)


class DomainClassifyServicer(object):
    """----------------
    Domain Classify
    ----------------
    """

    def DomainClassify(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DomainClassifyServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'DomainClassify': grpc.unary_unary_rpc_method_handler(
                    servicer.DomainClassify,
                    request_deserializer=app_dot_protos_dot_assistant__pb2.DomainClassifyRequest.FromString,
                    response_serializer=app_dot_protos_dot_assistant__pb2.DomainClassifyResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'app.DomainClassify', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('app.DomainClassify', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class DomainClassify(object):
    """----------------
    Domain Classify
    ----------------
    """

    @staticmethod
    def DomainClassify(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/app.DomainClassify/DomainClassify',
            app_dot_protos_dot_assistant__pb2.DomainClassifyRequest.SerializeToString,
            app_dot_protos_dot_assistant__pb2.DomainClassifyResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class IssueServiceStub(object):
    """----------------
    Issue bot service
    ----------------
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ResolveIssueServers = channel.unary_unary(
                '/app.IssueService/ResolveIssueServers',
                request_serializer=app_dot_protos_dot_assistant__pb2.ResolveIssueRequest.SerializeToString,
                response_deserializer=app_dot_protos_dot_assistant__pb2.ResolveIssueResponse.FromString,
                _registered_method=True)


class IssueServiceServicer(object):
    """----------------
    Issue bot service
    ----------------
    """

    def ResolveIssueServers(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_IssueServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ResolveIssueServers': grpc.unary_unary_rpc_method_handler(
                    servicer.ResolveIssueServers,
                    request_deserializer=app_dot_protos_dot_assistant__pb2.ResolveIssueRequest.FromString,
                    response_serializer=app_dot_protos_dot_assistant__pb2.ResolveIssueResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'app.IssueService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('app.IssueService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class IssueService(object):
    """----------------
    Issue bot service
    ----------------
    """

    @staticmethod
    def ResolveIssueServers(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/app.IssueService/ResolveIssueServers',
            app_dot_protos_dot_assistant__pb2.ResolveIssueRequest.SerializeToString,
            app_dot_protos_dot_assistant__pb2.ResolveIssueResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class NucleiTemplateServiceStub(object):
    """----------------
    Nuclei template gen 
    ----------------
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateTemplate = channel.unary_unary(
                '/app.NucleiTemplateService/CreateTemplate',
                request_serializer=app_dot_protos_dot_assistant__pb2.CreateTemplateRequest.SerializeToString,
                response_deserializer=app_dot_protos_dot_assistant__pb2.CreateTemplateResponse.FromString,
                _registered_method=True)


class NucleiTemplateServiceServicer(object):
    """----------------
    Nuclei template gen 
    ----------------
    """

    def CreateTemplate(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_NucleiTemplateServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateTemplate': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateTemplate,
                    request_deserializer=app_dot_protos_dot_assistant__pb2.CreateTemplateRequest.FromString,
                    response_serializer=app_dot_protos_dot_assistant__pb2.CreateTemplateResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'app.NucleiTemplateService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('app.NucleiTemplateService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class NucleiTemplateService(object):
    """----------------
    Nuclei template gen 
    ----------------
    """

    @staticmethod
    def CreateTemplate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/app.NucleiTemplateService/CreateTemplate',
            app_dot_protos_dot_assistant__pb2.CreateTemplateRequest.SerializeToString,
            app_dot_protos_dot_assistant__pb2.CreateTemplateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class ConversationServiceStub(object):
    """----------------
    Conversation
    ----------------
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetConversations = channel.unary_unary(
                '/app.ConversationService/GetConversations',
                request_serializer=app_dot_protos_dot_assistant__pb2.GetConversationsRequest.SerializeToString,
                response_deserializer=app_dot_protos_dot_assistant__pb2.GetConversationsResponse.FromString,
                _registered_method=True)
        self.UpdateConversation = channel.unary_unary(
                '/app.ConversationService/UpdateConversation',
                request_serializer=app_dot_protos_dot_assistant__pb2.UpdateConversationRequest.SerializeToString,
                response_deserializer=app_dot_protos_dot_assistant__pb2.UpdateConversationResponse.FromString,
                _registered_method=True)
        self.DeleteConversation = channel.unary_unary(
                '/app.ConversationService/DeleteConversation',
                request_serializer=app_dot_protos_dot_assistant__pb2.DeleteConversationRequest.SerializeToString,
                response_deserializer=app_dot_protos_dot_assistant__pb2.DeleteConversationResponse.FromString,
                _registered_method=True)
        self.DeleteConversations = channel.unary_unary(
                '/app.ConversationService/DeleteConversations',
                request_serializer=app_dot_protos_dot_assistant__pb2.DeleteConversationsRequest.SerializeToString,
                response_deserializer=app_dot_protos_dot_assistant__pb2.DeleteConversationsResponse.FromString,
                _registered_method=True)


class ConversationServiceServicer(object):
    """----------------
    Conversation
    ----------------
    """

    def GetConversations(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateConversation(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteConversation(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteConversations(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ConversationServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetConversations': grpc.unary_unary_rpc_method_handler(
                    servicer.GetConversations,
                    request_deserializer=app_dot_protos_dot_assistant__pb2.GetConversationsRequest.FromString,
                    response_serializer=app_dot_protos_dot_assistant__pb2.GetConversationsResponse.SerializeToString,
            ),
            'UpdateConversation': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateConversation,
                    request_deserializer=app_dot_protos_dot_assistant__pb2.UpdateConversationRequest.FromString,
                    response_serializer=app_dot_protos_dot_assistant__pb2.UpdateConversationResponse.SerializeToString,
            ),
            'DeleteConversation': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteConversation,
                    request_deserializer=app_dot_protos_dot_assistant__pb2.DeleteConversationRequest.FromString,
                    response_serializer=app_dot_protos_dot_assistant__pb2.DeleteConversationResponse.SerializeToString,
            ),
            'DeleteConversations': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteConversations,
                    request_deserializer=app_dot_protos_dot_assistant__pb2.DeleteConversationsRequest.FromString,
                    response_serializer=app_dot_protos_dot_assistant__pb2.DeleteConversationsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'app.ConversationService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('app.ConversationService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ConversationService(object):
    """----------------
    Conversation
    ----------------
    """

    @staticmethod
    def GetConversations(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/app.ConversationService/GetConversations',
            app_dot_protos_dot_assistant__pb2.GetConversationsRequest.SerializeToString,
            app_dot_protos_dot_assistant__pb2.GetConversationsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateConversation(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/app.ConversationService/UpdateConversation',
            app_dot_protos_dot_assistant__pb2.UpdateConversationRequest.SerializeToString,
            app_dot_protos_dot_assistant__pb2.UpdateConversationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteConversation(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/app.ConversationService/DeleteConversation',
            app_dot_protos_dot_assistant__pb2.DeleteConversationRequest.SerializeToString,
            app_dot_protos_dot_assistant__pb2.DeleteConversationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteConversations(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/app.ConversationService/DeleteConversations',
            app_dot_protos_dot_assistant__pb2.DeleteConversationsRequest.SerializeToString,
            app_dot_protos_dot_assistant__pb2.DeleteConversationsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class MessageServiceStub(object):
    """----------------
    Message
    ----------------
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetMessages = channel.unary_unary(
                '/app.MessageService/GetMessages',
                request_serializer=app_dot_protos_dot_assistant__pb2.GetMessagesRequest.SerializeToString,
                response_deserializer=app_dot_protos_dot_assistant__pb2.GetMessagesResponse.FromString,
                _registered_method=True)
        self.CreateMessage = channel.unary_stream(
                '/app.MessageService/CreateMessage',
                request_serializer=app_dot_protos_dot_assistant__pb2.CreateMessageRequest.SerializeToString,
                response_deserializer=app_dot_protos_dot_assistant__pb2.CreateMessageResponse.FromString,
                _registered_method=True)
        self.UpdateMessage = channel.unary_stream(
                '/app.MessageService/UpdateMessage',
                request_serializer=app_dot_protos_dot_assistant__pb2.UpdateMessageRequest.SerializeToString,
                response_deserializer=app_dot_protos_dot_assistant__pb2.UpdateMessageResponse.FromString,
                _registered_method=True)
        self.DeleteMessage = channel.unary_unary(
                '/app.MessageService/DeleteMessage',
                request_serializer=app_dot_protos_dot_assistant__pb2.DeleteMessageRequest.SerializeToString,
                response_deserializer=app_dot_protos_dot_assistant__pb2.DeleteMessageResponse.FromString,
                _registered_method=True)


class MessageServiceServicer(object):
    """----------------
    Message
    ----------------
    """

    def GetMessages(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateMessage(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateMessage(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteMessage(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MessageServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetMessages': grpc.unary_unary_rpc_method_handler(
                    servicer.GetMessages,
                    request_deserializer=app_dot_protos_dot_assistant__pb2.GetMessagesRequest.FromString,
                    response_serializer=app_dot_protos_dot_assistant__pb2.GetMessagesResponse.SerializeToString,
            ),
            'CreateMessage': grpc.unary_stream_rpc_method_handler(
                    servicer.CreateMessage,
                    request_deserializer=app_dot_protos_dot_assistant__pb2.CreateMessageRequest.FromString,
                    response_serializer=app_dot_protos_dot_assistant__pb2.CreateMessageResponse.SerializeToString,
            ),
            'UpdateMessage': grpc.unary_stream_rpc_method_handler(
                    servicer.UpdateMessage,
                    request_deserializer=app_dot_protos_dot_assistant__pb2.UpdateMessageRequest.FromString,
                    response_serializer=app_dot_protos_dot_assistant__pb2.UpdateMessageResponse.SerializeToString,
            ),
            'DeleteMessage': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteMessage,
                    request_deserializer=app_dot_protos_dot_assistant__pb2.DeleteMessageRequest.FromString,
                    response_serializer=app_dot_protos_dot_assistant__pb2.DeleteMessageResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'app.MessageService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('app.MessageService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class MessageService(object):
    """----------------
    Message
    ----------------
    """

    @staticmethod
    def GetMessages(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/app.MessageService/GetMessages',
            app_dot_protos_dot_assistant__pb2.GetMessagesRequest.SerializeToString,
            app_dot_protos_dot_assistant__pb2.GetMessagesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateMessage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/app.MessageService/CreateMessage',
            app_dot_protos_dot_assistant__pb2.CreateMessageRequest.SerializeToString,
            app_dot_protos_dot_assistant__pb2.CreateMessageResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateMessage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/app.MessageService/UpdateMessage',
            app_dot_protos_dot_assistant__pb2.UpdateMessageRequest.SerializeToString,
            app_dot_protos_dot_assistant__pb2.UpdateMessageResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteMessage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/app.MessageService/DeleteMessage',
            app_dot_protos_dot_assistant__pb2.DeleteMessageRequest.SerializeToString,
            app_dot_protos_dot_assistant__pb2.DeleteMessageResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class MCPServerServiceStub(object):
    """----------------
    MCP Server
    ----------------
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetMCPServers = channel.unary_unary(
                '/app.MCPServerService/GetMCPServers',
                request_serializer=app_dot_protos_dot_assistant__pb2.GetMCPServersRequest.SerializeToString,
                response_deserializer=app_dot_protos_dot_assistant__pb2.GetMCPServersResponse.FromString,
                _registered_method=True)
        self.AddMCPServers = channel.unary_unary(
                '/app.MCPServerService/AddMCPServers',
                request_serializer=app_dot_protos_dot_assistant__pb2.AddMCPServersRequest.SerializeToString,
                response_deserializer=app_dot_protos_dot_assistant__pb2.AddMCPServersResponse.FromString,
                _registered_method=True)
        self.UpdateMCPServers = channel.unary_unary(
                '/app.MCPServerService/UpdateMCPServers',
                request_serializer=app_dot_protos_dot_assistant__pb2.UpdateMCPServersRequest.SerializeToString,
                response_deserializer=app_dot_protos_dot_assistant__pb2.UpdateMCPServersResponse.FromString,
                _registered_method=True)
        self.DeleteMCPServers = channel.unary_unary(
                '/app.MCPServerService/DeleteMCPServers',
                request_serializer=app_dot_protos_dot_assistant__pb2.DeleteMCPServersRequest.SerializeToString,
                response_deserializer=app_dot_protos_dot_assistant__pb2.DeleteMCPServersResponse.FromString,
                _registered_method=True)
        self.GetMCPServerHealth = channel.unary_unary(
                '/app.MCPServerService/GetMCPServerHealth',
                request_serializer=app_dot_protos_dot_assistant__pb2.GetMCPServerHealthRequest.SerializeToString,
                response_deserializer=app_dot_protos_dot_assistant__pb2.GetMCPServerHealthResponse.FromString,
                _registered_method=True)


class MCPServerServiceServicer(object):
    """----------------
    MCP Server
    ----------------
    """

    def GetMCPServers(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AddMCPServers(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateMCPServers(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteMCPServers(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetMCPServerHealth(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MCPServerServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetMCPServers': grpc.unary_unary_rpc_method_handler(
                    servicer.GetMCPServers,
                    request_deserializer=app_dot_protos_dot_assistant__pb2.GetMCPServersRequest.FromString,
                    response_serializer=app_dot_protos_dot_assistant__pb2.GetMCPServersResponse.SerializeToString,
            ),
            'AddMCPServers': grpc.unary_unary_rpc_method_handler(
                    servicer.AddMCPServers,
                    request_deserializer=app_dot_protos_dot_assistant__pb2.AddMCPServersRequest.FromString,
                    response_serializer=app_dot_protos_dot_assistant__pb2.AddMCPServersResponse.SerializeToString,
            ),
            'UpdateMCPServers': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateMCPServers,
                    request_deserializer=app_dot_protos_dot_assistant__pb2.UpdateMCPServersRequest.FromString,
                    response_serializer=app_dot_protos_dot_assistant__pb2.UpdateMCPServersResponse.SerializeToString,
            ),
            'DeleteMCPServers': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteMCPServers,
                    request_deserializer=app_dot_protos_dot_assistant__pb2.DeleteMCPServersRequest.FromString,
                    response_serializer=app_dot_protos_dot_assistant__pb2.DeleteMCPServersResponse.SerializeToString,
            ),
            'GetMCPServerHealth': grpc.unary_unary_rpc_method_handler(
                    servicer.GetMCPServerHealth,
                    request_deserializer=app_dot_protos_dot_assistant__pb2.GetMCPServerHealthRequest.FromString,
                    response_serializer=app_dot_protos_dot_assistant__pb2.GetMCPServerHealthResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'app.MCPServerService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('app.MCPServerService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class MCPServerService(object):
    """----------------
    MCP Server
    ----------------
    """

    @staticmethod
    def GetMCPServers(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/app.MCPServerService/GetMCPServers',
            app_dot_protos_dot_assistant__pb2.GetMCPServersRequest.SerializeToString,
            app_dot_protos_dot_assistant__pb2.GetMCPServersResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AddMCPServers(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/app.MCPServerService/AddMCPServers',
            app_dot_protos_dot_assistant__pb2.AddMCPServersRequest.SerializeToString,
            app_dot_protos_dot_assistant__pb2.AddMCPServersResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateMCPServers(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/app.MCPServerService/UpdateMCPServers',
            app_dot_protos_dot_assistant__pb2.UpdateMCPServersRequest.SerializeToString,
            app_dot_protos_dot_assistant__pb2.UpdateMCPServersResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteMCPServers(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/app.MCPServerService/DeleteMCPServers',
            app_dot_protos_dot_assistant__pb2.DeleteMCPServersRequest.SerializeToString,
            app_dot_protos_dot_assistant__pb2.DeleteMCPServersResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetMCPServerHealth(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/app.MCPServerService/GetMCPServerHealth',
            app_dot_protos_dot_assistant__pb2.GetMCPServerHealthRequest.SerializeToString,
            app_dot_protos_dot_assistant__pb2.GetMCPServerHealthResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
